<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Conta corrente Gomes Bank</title>
</head>
<body>
<div style="margin-top: 10px">Greetings, Guilherme</div>
<div>Guilherme Gomes</b></div>
<br/>
<div>Parabéns! Você acaba de abrir uma conta no maior banco do mundo, Gomes Bank :)</div>
</body>
</html>